begin;
create extension if not exists vector with schema extensions;
create table if not exists public.aurora_documents (
  id bigint generated by default as identity primary key,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(1536) not null,
  source text not null,
  chunk_index integer not null,
  content_hash text not null,
  created_at timestamptz not null default now(),
  unique (source, chunk_index)
);
create index if not exists aurora_documents_metadata_idx
  on public.aurora_documents using gin (metadata);
create index if not exists aurora_documents_embedding_idx
  on public.aurora_documents using hnsw (embedding extensions.vector_cosine_ops);
alter table public.aurora_documents enable row level security;
revoke all on table public.aurora_documents from anon, authenticated;
grant all on table public.aurora_documents to service_role;
grant usage, select on sequence public.aurora_documents_id_seq to service_role;
create or replace function public.match_aurora_documents(
  query_embedding extensions.vector(1536),
  match_count integer default 5,
  filter jsonb default '{}'::jsonb
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  source text,
  chunk_index integer,
  similarity double precision
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    d.id,
    d.content,
    d.metadata,
    d.source,
    d.chunk_index,
    1 - (d.embedding operator(extensions.<=>) query_embedding) as similarity
  from public.aurora_documents d
  where d.metadata @> filter
  order by d.embedding operator(extensions.<=>) query_embedding
  limit greatest(match_count, 0);
$$;
revoke all on function public.match_aurora_documents(extensions.vector, integer, jsonb)
  from public, anon, authenticated;
grant execute on function public.match_aurora_documents(extensions.vector, integer, jsonb)
  to service_role;
create table if not exists public.city_cost_entries (
  id bigint generated by default as identity primary key,
  city text not null,
  country text not null default 'Canada',
  dataset_category text not null default 'cost-of-living',
  category_group text not null,
  item_name text not null,
  average_price numeric(12, 2) not null check (average_price >= 0),
  lowest_price numeric(12, 2) check (lowest_price is null or lowest_price >= 0),
  highest_price numeric(12, 2) check (highest_price is null or highest_price >= 0),
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  source_url text not null,
  source_name text not null,
  source_actor text,
  collected_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint city_cost_entries_price_range_check check (
    (lowest_price is null or lowest_price <= average_price)
    and (highest_price is null or highest_price >= average_price)
  ),
  constraint city_cost_entries_current_unique unique (
    city,
    category_group,
    item_name
  )
);
comment on table public.city_cost_entries is
  'Current cost-of-living values used by the city comparator.';
create index if not exists city_cost_entries_city_idx
  on public.city_cost_entries (city);
create index if not exists city_cost_entries_category_group_idx
  on public.city_cost_entries (category_group);
alter table public.city_cost_entries enable row level security;
revoke all on table public.city_cost_entries from anon, authenticated;
grant select on table public.city_cost_entries to authenticated;
grant all on table public.city_cost_entries to service_role;
grant usage, select on sequence public.city_cost_entries_id_seq to service_role;
drop policy if exists "Authenticated users can read city cost entries"
  on public.city_cost_entries;
create policy "Authenticated users can read city cost entries"
  on public.city_cost_entries
  for select
  to authenticated
  using (true);
create table if not exists public.canadian_city_catalog (
  city text primary key,
  province_code text not null check (province_code ~ '^[A-Z]{2}$'),
  province_name text not null,
  metro_area text not null,
  city_type text not null check (
    city_type in ('capital', 'territorial-capital', 'core', 'surrounding', 'important')
  ),
  has_cost_data boolean not null default false,
  item_count smallint not null default 0 check (item_count >= 0),
  last_collected_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.canadian_city_catalog is
  'Curated Canadian city coverage for the cost-of-living comparator.';
create index if not exists canadian_city_catalog_province_idx
  on public.canadian_city_catalog (province_code, city);
alter table public.canadian_city_catalog enable row level security;
revoke all on table public.canadian_city_catalog from anon, authenticated;
grant select on table public.canadian_city_catalog to authenticated;
grant all on table public.canadian_city_catalog to service_role;
drop policy if exists "Authenticated users can read Canadian city catalog"
  on public.canadian_city_catalog;
create policy "Authenticated users can read Canadian city catalog"
  on public.canadian_city_catalog
  for select
  to authenticated
  using (true);
commit;
